server.port=8082
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.ru.hogwarts.school=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=ERROR
spring.thymeleaf.cache=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
