server.port=8081
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.ru.hogwarts.school=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
spring.thymeleaf.cache=false
